name: GitHub Actions Practice
run-name: Testing a bunch of stuff 
on: 
  push:
    branches-ignore:
    - main

jobs:
  Check-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
      # will resolve python version from .python-version file
        uses: actions/setup-python@v4

      - uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Editor config check
        run: editorconfig-checker
      

  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
      # will resolve python version from .python-version file
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -a)"      
      - name: Run pylint
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -a)"
          pylint $(git ls-files '*.py')
  
  Black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  Markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yml
          files: '**/*.md'
          ignore: node_modules

  Unit-tests:
    needs: [Check-editorconfig, Pylint, Black, Markdown-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
      # will resolve python version from .python-version file
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
   
      - name: Run unit tests with pytest
        working-directory: ./app
        run: |
          python -m unittest
