name: GitHub Actions Practice
run-name: Testing a bunch of stuff 
on: 
  push:
    branches-ignore:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
      # will resolve python version from .python-version file
        uses: actions/setup-python@v4

      - uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Editor config check
        run: editorconfig-checker

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -a)"
      
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: . 

  Pylint:
    needs: Build
    runs-on: ubuntu-latest
    steps:      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: .
          
      - name: Run pylint
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -a)"
          pylint $(git ls-files '*.py')
  
  Format:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: .

      - name: Run black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  Markdown-lint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: .

      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '**/*.md'
          ignore: node_modules
          version: 0.28.1
